### ISSUE TITLE
Sites with no derived mutations lead to segfault

### ISSUE THREAD

**Issue by hyanwong** [vlshchur/argentum-pv#3]
e.g. an input file like this

```
0000000000000000
0000000010000000
0000000000000100
0001000001100000
0000000000000100
0000000010000000
1110111110011111
1010000000000001
0000010100010010
1110111110011111
0000000000000100
```

Gives

```
New ARGentum session initialised with 16 haplotypes.
Segmentation fault: 11
```

A more sensible error message would be good, or (even better), the ability to deal with non-variable sites.

**Comment by vlshchur** [comment]
This is fixed now. Trees are output at each site, both variable and non-variable. Thank you for catching it.

**Comment by hyanwong** [comment]
Works fine, thanks
